apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: nginx
              servicePort: {{ .Values.externalPort }}
