
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: {{ .Values.namespace }}
  labels:
    app: adminer
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: adminer
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: adminer
        ports:
          - containerPort: 8080
            name: port-http

