
apiVersion: v1
kind: Service
metadata:
  name: redis2
  namespace: {{ .Values.namespace }}
  labels:
    app: redis2
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: redis2
    release: {{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: 6379