apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: alex
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: nginx
              servicePort: 30081
