apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
   name: frontend
   namespace: {{ .Values.namespace }}
spec:
   hosts:
   - "*"
   gateways:
   - frontend
   http:
       - route:
           - destination:
               host: nginx
               port:
                   number: {{ .Values.externalPort }}