apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: postgres
    release: {{ .Release.Name }}
  ports:
    - port: 5432
      targetPort: 5432