apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Values.namespace }}
  labels:
    app: worker
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: worker
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: worker
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: '6379'