apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    release: {{ .Release.Name }}
spec:
  selector:
    app: nginx
    release: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: port-http
      protocol: TCP
      port: 30080
      targetPort: 80
      nodePort: 30080