apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    app: api
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: api
    release: {{ .Release.Name }}
  ports:
    - port: 5000
      targetPort: 5000